---
- hosts: devbox
  remote_user: adminuser

  tasks:
  - name: Add Microsoft APT key
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present
    become: yes

  - name: Add source repository into sources list
    become: yes
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-{{ ansible_distribution_release }}-prod {{ ansible_distribution_release }} main
      state: present

  - name: Install Azure Functions core tools
    become: yes
    ansible.builtin.apt:
      name: azure-functions-core-tools-4
      state: present
      update_cache: yes

  - name: Remove useless packages from the cache
    become: yes
    ansible.builtin.apt:
      autoclean: yes
      autoremove: yes
